export const defaultInvoices = [
  {
    id: "RT3080",
    status: "paid",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "Jensen Huang",
      clientEmail: "jensenhuang@mail.com",
      streetAdress: "123 Main Street",
      city: "Los Angeles",
      postalCode: "90001",
      country: "United States",
      date: "10.08.2021",
      paymentTerms: "19.08.2021",
      projectDescription: "Website Development",
    },
    itemList: [
      {
        itemName: "Web Development",
        quantity: 1,
        price: 1800.9,
      },
    ],
    totalPrice: 1800.9,
  },
  {
    id: "XM9141",
    status: "pending",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "Alex Grim",
      clientEmail: "alexgrim@mail.com",
      streetAdress: "84 Church Way",
      city: "Bradford",
      postalCode: "BD1 9PB",
      country: "United Kingdom",
      date: "21.08.2021",
      paymentTerms: "20.09.2021",
      projectDescription: "Graphic Design",
    },
    itemList: [
      {
        itemName: "Banner Design",
        quantity: 1,
        price: 156,
      },
      {
        itemName: "Email Design",
        quantity: 2,
        price: 200,
      },
    ],
    totalPrice: 556,
  },
  {
    id: "RG0314",
    status: "paid",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "John Morrison",
      clientEmail: "john@mail.com",
      streetAdress: "456 Elm Street",
      city: "New York",
      postalCode: "10001",
      country: "United States",
      date: "15.09.2021",
      paymentTerms: "01.10.2021",
      projectDescription: "App Development",
    },
    itemList: [
      {
        itemName: "Mobile App",
        quantity: 1,
        price: 14002.33,
      },
    ],
    totalPrice: 14002.33,
  },
  {
    id: "RT2080",
    status: "pending",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "Alysa Werner",
      clientEmail: "alysa@mail.com",
      streetAdress: "789 Oak Avenue",
      city: "Chicago",
      postalCode: "60601",
      country: "United States",
      date: "25.09.2021",
      paymentTerms: "12.10.2021",
      projectDescription: "Logo Design",
    },
    itemList: [
      {
        itemName: "Logo Design",
        quantity: 1,
        price: 102.04,
      },
    ],
    totalPrice: 102.04,
  },
  {
    id: "AA1449",
    status: "pending",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "Mellisa Clarke",
      clientEmail: "mellisa@mail.com",
      streetAdress: "567 Pine Street",
      city: "San Francisco",
      postalCode: "94101",
      country: "United States",
      date: "28.09.2021",
      paymentTerms: "14.10.2021",
      projectDescription: "Social Media Marketing",
    },
    itemList: [
      {
        itemName: "Social Media Campaign",
        quantity: 1,
        price: 4032.33,
      },
    ],
    totalPrice: 4032.33,
  },
  {
    id: "TY9141",
    status: "pending",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "Thomas Wayne",
      clientEmail: "thomas@mail.com",
      streetAdress: "678 Maple Street",
      city: "Gotham City",
      postalCode: "12345",
      country: "United States",
      date: "02.10.2021",
      paymentTerms: "31.10.2021",
      projectDescription: "Consulting Services",
    },
    itemList: [
      {
        itemName: "Consulting",
        quantity: 1,
        price: 6155.91,
      },
    ],
    totalPrice: 6155.91,
  },
  {
    id: "FV2353",
    status: "draft",
    from: {
      streetAdress: "19 Union Terrace",
      city: "London",
      postalCode: "E1 3EZ",
      country: "United Kingdom",
    },
    to: {
      clientName: "Anita Wainwright",
      clientEmail: "anita@mail.com",
      streetAdress: "789 Cedar Lane",
      city: "London",
      postalCode: "SW1A 1AA",
      country: "United Kingdom",
      date: "15.11.2021",
      paymentTerms: "12.11.2021",
      projectDescription: "Content Writing",
    },
    itemList: [
      {
        itemName: "Blog Articles",
        quantity: 3,
        price: 1000.68,
      },
      {
        itemName: "Website Copy",
        quantity: 1,
        price: 2101.36,
      },
    ],
    totalPrice: 3102.04,
  },
];
