export const breakpoint = {
  tabletMax: 1200,
  mobileMax: 950,
};

const colorNames = {
  white: "#FFFFFF",
  cornflowerBlue: "#7C5DFA",
  heliotrope: "#9277FF",
  mirage: "#1E2139",
  ebonyClay: "#252945",
  selago: "#DFE3FA",
  baliHai: "#888EB0",
  shipCove: "#7E88C3",
  vulcan: "#0C0E16",
  burntSienna: "#EC5757",
  monaLisa: "#FF9797",
  whisper: "#F8F8FB",
  cinder: "#141625",
  fiord: "#494E6E",
  shamrock: "#33D69F",
  pizazz: "#FF8F00",
  oxfordBlue: "#373B53",
  wildBlueYonder: "#858BB2",
  whiteLilac: "#F9FAFE",
  waterloo: "#777F98",
};

export const lightTheme = {
  main: {
    background: colorNames.whisper,
    mainText: colorNames.vulcan,
    text1: colorNames.baliHai,
    arrow: colorNames.cornflowerBlue,
  },
  filterSelector: {
    background: colorNames.white,
    text: colorNames.vulcan,
    box: colorNames.cornflowerBlue,
  },
  newInvoiceButton: {
    background: colorNames.heliotrope,
    text: colorNames.white,
  },
  bar: {
    background: colorNames.oxfordBlue,
    themeIcon: colorNames.shipCove,
    themeIconHover: colorNames.selago,
    line: colorNames.fiord,
  },
  tile: {
    background: colorNames.white,
    mainText: colorNames.vulcan,
    hash: colorNames.shipCove,
    text1: colorNames.baliHai,
    text2: colorNames.shipCove,
    text3: colorNames.wildBlueYonder,
    paid: colorNames.shamrock,
    pending: colorNames.pizazz,
    draft: colorNames.oxfordBlue,
    arrow: colorNames.cornflowerBlue,
    border: colorNames.cornflowerBlue,
    editBackground: colorNames.whiteLilac,
    editText: colorNames.shipCove,
    deleteBackground: colorNames.burntSienna,
    deleteText: colorNames.white,
    markPaidBackground: colorNames.cornflowerBlue,
    markPaidText: colorNames.white,
  },
  invoiceDetailsTile: {
    background: colorNames.white,
    mainText: colorNames.vulcan,
    hash: colorNames.baliHai,
    text1: colorNames.shipCove,
    rectangleBackground: colorNames.whiteLilac,
    rectangleFooter: colorNames.oxfordBlue,
    rectangleFooterText: colorNames.white,
  },
  createInvoice: {
    background: colorNames.white,
    mainText: colorNames.vulcan,
    hash: colorNames.baliHai,
    inputBackground: colorNames.white,
    inputBorder: colorNames.selago,
    inputName: colorNames.shipCove,
    invalidInput: colorNames.burntSienna,
    fieldsetText: colorNames.cornflowerBlue,
    itemListText: colorNames.waterloo,
    totalPrice: colorNames.baliHai,
    bottomButtonBackground: colorNames.whiteLilac,
    bottomButtonText: colorNames.shipCove,
    saveDraftBackground: colorNames.oxfordBlue,
    saveDraftText: colorNames.baliHai,
    saveSendBackground: colorNames.cornflowerBlue,
    saveSendText: colorNames.white,
  },
  deletionWindow: {
    background: colorNames.white,
    mainText: colorNames.vulcan,
    text1: colorNames.baliHai,
    cancelBackground: colorNames.whiteLilac,
    cancelText: colorNames.shipCove,
    deleteBackground: colorNames.burntSienna,
    deleteText: colorNames.white,
  },
  breakpoint,
};

export const darkTheme = {
  main: {
    background: colorNames.cinder,
    mainText: colorNames.white,
    text1: colorNames.selago,
    arrow: colorNames.cornflowerBlue,
  },
  filterSelector: {
    background: colorNames.ebonyClay,
    text: colorNames.white,
    box: colorNames.cornflowerBlue,
  },
  newInvoiceButton: {
    background: colorNames.heliotrope,
    text: colorNames.white,
  },
  bar: {
    background: colorNames.mirage,
    themeIcon: colorNames.wildBlueYonder,
    themeIconHover: colorNames.selago,
    line: colorNames.fiord,
  },
  tile: {
    background: colorNames.mirage,
    mainText: colorNames.white,
    hash: colorNames.shipCove,
    text1: colorNames.selago,
    text2: colorNames.selago,
    text3: colorNames.white,
    paid: colorNames.shamrock,
    pending: colorNames.pizazz,
    draft: colorNames.selago,
    arrow: colorNames.cornflowerBlue,
    border: colorNames.cornflowerBlue,
    editBackground: colorNames.ebonyClay,
    editText: colorNames.selago,
    deleteBackground: colorNames.burntSienna,
    deleteText: colorNames.white,
    markPaidBackground: colorNames.cornflowerBlue,
    markPaidText: colorNames.white,
  },
  invoiceDetailsTile: {
    background: colorNames.mirage,
    mainText: colorNames.white,
    hash: colorNames.baliHai,
    text1: colorNames.selago,
    rectangleBackground: colorNames.ebonyClay,
    rectangleFooter: colorNames.vulcan,
    rectangleFooterText: colorNames.white,
  },
  createInvoice: {
    background: colorNames.cinder,
    mainText: colorNames.white,
    hash: colorNames.baliHai,
    inputBackground: colorNames.mirage,
    inputBorder: colorNames.ebonyClay,
    inputName: colorNames.selago,
    invalidInput: colorNames.burntSienna,
    fieldsetText: colorNames.cornflowerBlue,
    itemListText: colorNames.waterloo,
    totalPrice: colorNames.selago,
    bottomButtonBackground: colorNames.ebonyClay,
    bottomButtonText: colorNames.selago,
    saveDraftBackground: colorNames.oxfordBlue,
    saveDraftText: colorNames.selago,
    saveSendBackground: colorNames.cornflowerBlue,
    saveSendText: colorNames.white,
  },
  deletionWindow: {
    background: colorNames.mirage,
    mainText: colorNames.white,
    text1: colorNames.selago,
    cancelBackground: colorNames.ebonyClay,
    cancelText: colorNames.selago,
    deleteBackground: colorNames.burntSienna,
    deleteText: colorNames.white,
  },
  breakpoint,
};
